### ISSUE TITLE
Initialize project.

### ISSUE THREAD

**Issue by proofit404** [proofit404/wiktionary#1]
```toml
[tool.poetry]
name = "wiktionary-org"
version = "0.0.1.dev0"
description = "Wiktionary on-demand scrapper."
authors = ["Josiah Kaviani <proofit404@gmail.com>"]
license = "BSD-2-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
